// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Selu383.SP25.Api;

#nullable disable

namespace Selu383.SP25.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250206222557_AddTheaterSeedDataa")]
    partial class AddTheaterSeedDataa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Selu383.SP25.Api.Models.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1200 W University Ave, Hammond, LA 70401",
                            Name = "AMC Hammond Square 8",
                            SeatCount = 1200
                        },
                        new
                        {
                            Id = 2,
                            Address = "1950 Gause Blvd W, Slidell, LA 70460",
                            Name = "Grand Cinema Slidell",
                            SeatCount = 800
                        },
                        new
                        {
                            Id = 3,
                            Address = "201 N US Highway 190, Covington, LA 70433",
                            Name = "Movie Tavern Covington",
                            SeatCount = 950
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
